#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

if (!file_exists(__DIR__.'/vendor/autoload.php')) {
    fwrite(STDERR, "Dependencies are not installed. Run composer install.\n");
    exit(1);
}

require __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput(),
    new Symfony\Component\Console\Output\ConsoleOutput()
);

$kernel->terminate($input, $status);

exit($status);
